{% set name = "fudge" %}
  {% set version = "1.1.1" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d9929d87bb38711112734d99a2c7ada5dc39ef67b758b1e55f4c779c3634efdc

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
  - pip
  - python
  run:
  - python

test:
  imports:
  - fudge
  - fudge.tests
  - fudge.tests.support

about:
  home: https://github.com/fudge-py/fudge
  license: The MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Replace real objects with fakes (mocks, stubs, etc) while testing.
  doc_url: http://farmdev.com/projects/fudge/index.html
  dev_url: https://github.com/fudge-py/fudge

extra:
  recipe-maintainers:
  - andreyz4k
